Transform: AWS::Serverless-2016-10-31
Parameters:
  DestinationEmailParameter:
    Type: String
    Default: vbudilov@somedomain.com
  RegionParameter:
    Type: String
    Default: us-east-1
Resources:
  EmailServiceLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.budilov.lambda.ses.Main::handleRequest
      FunctionName: EmailServiceLambda
      Policies:
       - AmazonSESFullAccess
      Runtime: java8
      MemorySize: 1024
      Timeout: 20
      CodeUri: target/lambda-ses-1.3-SNAPSHOT.jar
      Environment:
        Variables:
          DESTINATION_EMAIL:
            Ref: DestinationEmailParameter
          REGION:
            Ref: RegionParameter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /email
            Method: post